# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1b140768ec1a334f2906f1e90d58b8c8dc45ac7927cb3a6adc2b429715acd5baf4533531a2a9639f6f815388cf3c741412ae2e8b3186a7b3d920db4dea3f9ba0

test:
  secret_key_base: 1874d4aa84d8a13c07c895097b782987922da9e8c311b4383e23ef2cdea3b2ce9a9c03cdd9f24d191bd45a500307105a77798089d5b65b2e7a96235b20e915f7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
